services:
  mysql:
    image: mysql:8.0
    container_name: lock-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: lockdb
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7
    container_name: lock-redis
    ports:
      - "6379:6379"
